[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[functions."*"]]
  timeout = 10
  node_bundler = "esbuild"
  external_node_modules = ["mongodb", "mongodb-client-encryption", "aws4"]
  included_files = ["./lib/mongodb.ts"]
  # Uncomment if using Node 18+
  # node_version = "18"

# For MongoDB connection stability
[build.environment]
  NODE_OPTIONS = "--max_old_space_size=4096"